# Generated by Django 5.2.13 on 2026-04-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_id", models.IntegerField()),
                ("customer", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=300)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("RPZ", "RPZ — Reduced Pressure Zone"),
                            ("DCVA", "DCVA — Double Check Valve"),
                            ("PVB", "PVB — Pressure Vacuum Breaker"),
                            ("SVB", "SVB — Spill-Resistant Vacuum Breaker"),
                            ("RPDA", "RPDA — Reduced Pressure Detector"),
                        ],
                        max_length=10,
                    ),
                ),
                ("device_size", models.CharField(max_length=10)),
                ("manufacturer", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("serial", models.CharField(max_length=100)),
                ("install_year", models.IntegerField(blank=True, null=True)),
                ("test_date", models.DateField()),
                ("test_time", models.TimeField()),
                (
                    "cv1_result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("closed", "Closed"),
                            ("leaked", "Leaked"),
                            ("opened", "Opened at PSI"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "cv1_psi",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                (
                    "cv2_result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("closed", "Closed"),
                            ("leaked", "Leaked"),
                            ("opened", "Opened at PSI"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "cv2_psi",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                (
                    "rv_result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("opened_ok", "Opened OK"),
                            ("did_not_open", "Did Not Open"),
                            ("leaked", "Leaked"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "rv_psi",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                (
                    "line_psi",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                (
                    "overall_result",
                    models.CharField(
                        choices=[("pass", "Pass"), ("fail", "Fail")], max_length=10
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("technician_initials", models.CharField(max_length=4)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("utility_submitted", models.BooleanField(default=False)),
                ("utility_submitted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={"ordering": ["-submitted_at"],},
        ),
    ]
