# Generated by Django 5.2.13 on 2026-04-27 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technician", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(model_name="testresult", name="job_id",),
        migrations.AddField(
            model_name="testresult",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="test_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="device_type",
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=300)),
                ("contact", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("scheduled_date", models.DateField()),
                ("scheduled_time", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("RPZ", "RPZ — Reduced Pressure Zone"),
                            ("DCVA", "DCVA — Double Check Valve"),
                            ("PVB", "PVB — Pressure Vacuum Breaker"),
                            ("SVB", "SVB — Spill-Resistant Vacuum Breaker"),
                            ("RPDA", "RPDA — Reduced Pressure Detector"),
                        ],
                        default="RPZ",
                        max_length=10,
                    ),
                ),
                ("device_size", models.CharField(blank=True, max_length=10)),
                ("device_make", models.CharField(blank=True, max_length=100)),
                ("device_model", models.CharField(blank=True, max_length=100)),
                ("serial", models.CharField(blank=True, max_length=100)),
                ("device_notes", models.TextField(blank=True)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lng", models.FloatField(blank=True, null=True)),
                ("device_lat", models.FloatField(blank=True, null=True)),
                ("device_lng", models.FloatField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["scheduled_date", "scheduled_time"],},
        ),
        migrations.AddField(
            model_name="testresult",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="test_results",
                to="technician.job",
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("technician", "Technician"),
                            ("operations", "Operations"),
                            ("manager", "Manager"),
                        ],
                        default="technician",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
