# Generated by Django 5.2.13 on 2026-04-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "technician",
            "0002_remove_testresult_job_id_testresult_submitted_by_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("technician", "Technician"),
                    ("operations", "Operations"),
                    ("manager", "Manager"),
                    ("admin", "Administrator"),
                ],
                default="technician",
                max_length=20,
            ),
        ),
    ]
