# Generated by Django 5.2.13 on 2026-04-28 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technician", "0003_alter_userprofile_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("technician", "Technician"),
                    ("operations", "Operations"),
                    ("manager", "Manager"),
                    ("admin", "Administrator"),
                    ("customer", "Customer"),
                ],
                default="technician",
                max_length=20,
            ),
        ),
    ]
