# Generated by Django 5.2.13 on 2026-04-28 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technician", "0005_add_customer_model_and_job_jurisdiction"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="device_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="device_lng",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="lng",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
