# Generated by Django 5.2.13 on 2026-04-29 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technician", "0006_customer_latlng"),
    ]

    operations = [
        migrations.AddField(
            model_name="testresult",
            name="hazard_level",
            field=models.CharField(
                blank=True,
                choices=[("low", "Low Hazard"), ("high", "High Hazard")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="testresult",
            name="service_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("domestic", "Domestic"),
                    ("irrigation", "Irrigation"),
                    ("fire", "Fire Protection"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="testresult",
            name="utility_account_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="testresult",
            name="utility_reference_number",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
