# Generated by Django 5.2.13 on 2026-04-29 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technician", "0007_utility_fields_on_testresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="counties",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_licensed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="license_expires",
            field=models.DateField(blank=True, null=True),
        ),
    ]
