# Generated by Django 5.2.13 on 2026-05-29 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technician", "0010_activity_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="website",
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.CreateModel(
            name="CustomerLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(default="Main", max_length=100)),
                ("address", models.CharField(blank=True, max_length=300)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(default="FL", max_length=2)),
                ("county", models.CharField(blank=True, max_length=100)),
                ("zip_code", models.CharField(blank=True, max_length=10)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lng", models.FloatField(blank=True, null=True)),
                ("device_lat", models.FloatField(blank=True, null=True)),
                ("device_lng", models.FloatField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="technician.customer",
                    ),
                ),
            ],
            options={"ordering": ["label"],},
        ),
    ]
