# Generated by Django 5.2.13 on 2026-05-29 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technician", "0011_website_and_customer_locations"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="location_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="technician.customerlocation",
            ),
        ),
    ]
