# Generated by Django 5.2.13 on 2026-05-29 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technician", "0012_job_location_ref"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
