# Generated by Django 5.2.13 on 2026-05-29 06:09

from django.db import migrations, models


def set_all_demo(apps, schema_editor):
    Customer = apps.get_model("technician", "Customer")
    Customer.objects.all().update(demo=True)


class Migration(migrations.Migration):

    dependencies = [
        ("technician", "0013_customer_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="demo",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_all_demo, migrations.RunPython.noop),
    ]
