# Generated by Django 5.2.13 on 2026-05-29 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("technician", "0014_customer_demo_flag"),
    ]

    operations = [
        migrations.AlterModelTable(name="customer", table="cust_customer",),
        migrations.AlterModelTable(
            name="customerlocation", table="cust_customerlocation",
        ),
    ]
